/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainGamesIndexRouteImport } from './routes/_main/games/index'
import { Route as MainGamesGtaSanAndreasRouteImport } from './routes/_main/games/gta/san-andreas'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainGamesIndexRoute = MainGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainGamesGtaSanAndreasRoute = MainGamesGtaSanAndreasRouteImport.update({
  id: '/games/gta/san-andreas',
  path: '/games/gta/san-andreas',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/': typeof MainIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/games/gta/san-andreas': typeof MainGamesGtaSanAndreasRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof MainIndexRoute
  '/games': typeof MainGamesIndexRoute
  '/games/gta/san-andreas': typeof MainGamesGtaSanAndreasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/_main/': typeof MainIndexRoute
  '/_main/games/': typeof MainGamesIndexRoute
  '/_main/games/gta/san-andreas': typeof MainGamesGtaSanAndreasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/signin' | '/' | '/games' | '/games/gta/san-andreas'
  fileRoutesByTo: FileRoutesByTo
  to: '/signin' | '/' | '/games' | '/games/gta/san-andreas'
  id:
    | '__root__'
    | '/_main'
    | '/signin'
    | '/_main/'
    | '/_main/games/'
    | '/_main/games/gta/san-andreas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/games/': {
      id: '/_main/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof MainGamesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/games/gta/san-andreas': {
      id: '/_main/games/gta/san-andreas'
      path: '/games/gta/san-andreas'
      fullPath: '/games/gta/san-andreas'
      preLoaderRoute: typeof MainGamesGtaSanAndreasRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainGamesIndexRoute: typeof MainGamesIndexRoute
  MainGamesGtaSanAndreasRoute: typeof MainGamesGtaSanAndreasRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainGamesIndexRoute: MainGamesIndexRoute,
  MainGamesGtaSanAndreasRoute: MainGamesGtaSanAndreasRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
